mode: serving_disagg_colocated
request_configuration: ../tests/rt_serving_baseline/inputs/overlapping_requests.json
request_metrics_output: ../tests/rt_analytical/outputs/serving_metrics.csv
request_summary_output: ../tests/rt_analytical/outputs/serving_summary.json
request_run_metadata_output: ../tests/rt_analytical/outputs/serving_metadata.json
workload_configuration: empty
comm_group_configuration: empty
system_configuration: ../tests/rt_serving_baseline/inputs/system_cfg.json
remote_memory_configuration: ../tests/rt_serving_baseline/inputs/remote_memory_cfg.json
network_configuration: ../tests/rt_serving_baseline/inputs/network_cfg.yml
logging_configuration: empty
logging_folder: ../tests/rt_analytical/outputs/log
num_queues_per_dim: 1
compute_scale: 1.0
comm_scale: 1.0
injection_scale: 1.0
rendezvous_protocol: false
